/*
 * stages.js — stage layouts.
 * Every stage is generated from a seed, so it is identical on every play.
 * Hazards are sized from the squad an attentive player is expected to have at that
 * point (est.N soldiers, weapon est.W), then scaled by per-stage difficulty factors
 * that tools/balance.js calibrates with the bots.
 */
(function (root) {
  'use strict';
  const ZGR = root.ZGR;
  const { Rng, C, make, weaponDps, clamp, MAX_WEAPON } = ZGR;

  const STAGE_COUNT = 30;
  const SEG_GAP = 430;

  // Per-stage calibration: [hazard factor, boss factor, star2 survivors, star3 survivors].
  // Generated by `node tools/balance.js --calibrate`; bosses of stages 20-30 were then softened
  // by hand so the normal bot wins most runs.
  const CALIB = [
    [0.9, 3.25, 52, 103], // 1
    [0.9, 2.938, 52, 105], // 2
    [0.9, 1.388, 22, 44], // 3
    [0.913, 2.781, 41, 81], // 4
    [0.926, 3.875, 56, 112], // 5
    [0.939, 2.313, 22, 45], // 6
    [0.952, 2.313, 38, 76], // 7
    [0.965, 1.913, 106, 212], // 8
    [0.978, 2, 61, 122], // 9
    [0.991, 2.469, 13, 25], // 10
    [1.004, 1.825, 116, 232], // 11
    [1.017, 2.781, 80, 160], // 12
    [1.03, 1.825, 45, 90], // 13
    [1.043, 3.25, 37, 74], // 14
    [1.056, 1.475, 55, 110], // 15
    [1.069, 1.913, 56, 112], // 16
    [1.082, 1.563, 47, 94], // 17
    [1.095, 3.25, 68, 136], // 18
    [1.108, 1.125, 24, 49], // 19
    [1.121, 1.247, 77, 154], // 20
    [1.134, 1.969, 99, 199], // 21
    [1.147, 1.969, 19, 39], // 22
    [1.16, 0.521, 36, 73], // 23
    [1.173, 1.303, 260, 521], // 24
    [1.186, 1.369, 184, 368], // 25
    [1.199, 1.237, 103, 206], // 26
    [1.212, 1.5, 37, 74], // 27
    [1.225, 2.888, 57, 115], // 28
    [1.238, 1.444, 50, 101], // 29
    [1.251, 2.554, 70, 141], // 30
  ];

  function niceRound(v) {
    v = Math.max(1, v);
    if (v < 20) return Math.round(v);
    if (v < 100) return Math.round(v / 5) * 5;
    if (v < 1000) return Math.round(v / 10) * 10;
    return Math.round(v / 50) * 50;
  }

  const HINTS = {
    'gates:easy': '드래그해서 파란 게이트로! 병력이 늘어납니다.',
    'horde:walker': '좀비 무리! 부딪히면 그 숫자만큼 병사를 잃어요. 먼저 쏴서 줄이세요.',
    'gates:addmul': '지금 병력이면 + 와 × 중 어느 쪽이 더 이득일까요?',
    'barrel:troops': '배럴을 쏴서 부수면 보상을 받아요.',
    'gates:flip': '게이트 숫자는 쏘면 커져요. 빨간 −도 계속 쏘면 +로 바뀝니다!',
    'barrel:weapon': '무기 배럴을 부수면 무기가 한 단계 강해져요.',
    'obst:spikes': '가시 바리케이드는 피해서 지나가세요.',
    'obst:tires': '타이어 더미는 쏴서 부술 수 있어요.',
    'gates:lesser': '둘 다 손해라면 덜 잃는 쪽을 고르세요.',
    'obst:saw': '톱날이 좌우로 움직여요. 타이밍을 보세요.',
    brute: '거대 좀비는 많이 쏴 둘수록 부딪혔을 때 피해가 줄어요.',
    'barrel:rapid': '연사 배럴: 8초 동안 두 배로 빨리 쏩니다.',
    'combo:bombHorde': '폭탄 배럴을 터뜨리면 주변 좀비가 한꺼번에 날아가요.',
    'barrel:freeze': '빙결 배럴: 6초 동안 적이 느려져요.',
    'horde:runner': '돌격 좀비는 빠릅니다. 미리 조준하세요.',
    'horde:static': '길을 막은 좀비 떼. 쏘거나 피하세요.',
  };

  // Hand-made sequences that introduce one idea at a time. `*` marks a segment that shows a hint.
  const INTRO_PLANS = {
    1: ['gates:easy*', 'horde:walker*', 'gates:addmul*', 'barrel:troops*', 'gates:flip*', 'horde:static', 'barrel:weapon*', 'gates:bothgood'],
    2: ['gates:easy', 'obst:spikes*', 'horde:walker', 'gates:addmul', 'obst:tires*', 'barrel:weapon', 'horde:walker', 'gates:lesser*', 'barrel:troops', 'gates:bothgood'],
    3: ['gates:addmul', 'horde:walker', 'obst:saw*', 'barrel:weapon', 'brute*', 'gates:flip', 'horde:static', 'barrel:troops', 'gates:addmul'],
    4: ['gates:easy', 'barrel:rapid*', 'horde:static', 'gates:addmul', 'combo:bombHorde*', 'barrel:weapon', 'barrel:freeze*', 'horde:runner*', 'gates:bothgood'],
    5: ['gates:addmul', 'horde:walker', 'barrel2', 'obst:saw', 'gates:lesser', 'brute', 'barrel:weapon', 'horde:runner', 'gates:flip', 'horde:walker', 'gates:addmul'],
  };

  // ---------- builder ----------
  function Builder(seed, opts) {
    this.rng = new Rng(seed);
    this.ents = [];
    this.pair = 0;
    this.est = { N: opts.startCount, W: opts.startWeapon || 1 };
    this.kH = opts.kH;
    this.s = opts.s;
    this.lastGateZ = -9999;
    this.lastBlockZ = -9999;
    this.hints = !!opts.hints;
  }

  Builder.prototype.dps = function () {
    return weaponDps(this.est.N, this.est.W);
  };

  // Firepower of a player who is doing noticeably worse than expected.
  Builder.prototype.dpsSafe = function () {
    return weaponDps(Math.max(1, this.est.N * 0.55), Math.max(1, this.est.W - (this.est.W > 2 ? 1 : 0)));
  };

  // Share of a volley that lands on a target `width` wide when the formation is centred on it.
  Builder.prototype.coverage = function (width, n) {
    n = Math.max(1, n === undefined ? this.est.N : n);
    return ZGR.volleyHits(n, 0, -width / 2, width / 2) / ZGR.bulletsPerVolley(n);
  };

  Builder.prototype.push = function (e, hintKey) {
    if (e.kind !== 'saw' && e.kind !== 'spikes') this.lastBlockZ = Math.max(this.lastBlockZ, e.z);
    if (hintKey && this.hints && HINTS[hintKey] && !this._hinted) {
      e.hint = HINTS[hintKey];
      this._hinted = true;
    }
    this.ents.push(e);
    return e;
  };

  // Seconds of free shooting a hazard at z gets once the squad is past the last gate pair.
  Builder.prototype.fireWindow = function (z, style) {
    const gap = z - (style === 'static' || style === 'barrel' ? this.lastBlockZ : this.lastGateZ);
    const inRange = C.BULLET_RANGE / C.RUN_SPEED;
    if (style === 'static' || style === 'barrel') return clamp(gap / C.RUN_SPEED, 0.6, inRange);
    const speed = style === 'runner' ? 95 : 40;
    const walked = (speed * Math.max(0, 900 - gap)) / C.RUN_SPEED;
    return clamp((gap - walked) / (C.RUN_SPEED + speed), 0.4, inRange);
  };

  Builder.prototype.gates = function (z, variant, hintKey) {
    const r = this.rng;
    const N = this.est.N;
    const dps = this.dps();
    const budget = N * 0.6 + 10; // points an attentive player adds by pumping a gate
    const hpPerPoint = Math.max(0.35, (dps * 3) / budget);
    const soft = Math.max(25, N * 0.8);
    let a;
    let b;
    switch (variant) {
      case 'easy':
        a = { op: 'add', v: niceRound(Math.max(4, N * r.f(0.35, 0.8) + 3)) };
        b = { op: 'add', v: -niceRound(Math.max(3, N * r.f(0.2, 0.45) + 2)) };
        break;
      case 'addmul': {
        const m = N < 40 ? r.pick([2, 2, 3]) : r.pick([2, 2, 2, 3]);
        a = { op: 'mul', v: m };
        b = { op: 'add', v: niceRound(Math.max(5, N * (m - 1) * r.f(0.55, 1.35) + 4)) };
        break;
      }
      case 'lesser':
        a = { op: 'add', v: -niceRound(Math.max(3, N * r.f(0.25, 0.6))) };
        b = { op: 'div', v: N > 60 && r.chance(0.3) ? 3 : 2 };
        break;
      case 'flip':
        a = { op: 'add', v: -niceRound(Math.max(3, budget * r.f(0.3, 0.6))) };
        b = { op: 'add', v: -niceRound(Math.max(6, N * r.f(0.45, 0.8) + 4)) };
        break;
      case 'bothgood':
      default:
        a = { op: 'mul', v: 2 };
        b = { op: 'add', v: niceRound(Math.max(6, N * r.f(0.6, 1.3) + 5)) };
        break;
    }
    if (r.chance(0.5)) {
      const t = a;
      a = b;
      b = t;
    }
    const pair = ++this.pair;
    const extra = { hpPerPoint, soft };
    this.push(make.gate(z, -C.ROAD_HALF, 0, a.op, a.v, pair, extra), hintKey);
    this.push(make.gate(z, 0, C.ROAD_HALF, b.op, b.v, pair, extra));
    // expected outcome: mostly the better gate, pumped a little, with some allowance for mistakes
    const bump = (gate) => (gate.op === 'add' ? { op: 'add', v: gate.v + budget * 0.3 } : gate);
    const ra = ZGR.gateResult(N, bump(a));
    const rb = ZGR.gateResult(N, bump(b));
    this.est.N = clamp(0.8 * Math.max(ra, rb) + 0.2 * Math.min(ra, rb), 1, C.MAX_SQUAD);
    this.lastGateZ = z;
  };

  Builder.prototype.horde = function (z, style, hintKey, mult) {
    const r = this.rng;
    const N = this.est.N;
    const dps = this.dps();
    const T = this.fireWindow(z, style);
    const pool = dps * T * this.kH * r.f(0.88, 1.12) * (mult || 1);
    const zh = Math.max(1, Math.round(pool / Math.max(12, N * 1.1)));
    const count = Math.max(4, Math.round(pool / zh));
    let x;
    if (style === 'static') x = r.pick([-80, 0, 80]) + r.f(-10, 10);
    else x = r.f(-90, 90);
    this.push(make.horde(z, x, count, zh, style), hintKey);
    const lost = Math.max(0, pool - dps * T * 0.95) / zh;
    this.est.N = Math.max(1, N - lost);
  };

  Builder.prototype.brute = function (z, hintKey) {
    const r = this.rng;
    const N = this.est.N;
    const dps = this.dps();
    const T = this.fireWindow(z, 'walker');
    const hp = Math.ceil(dps * this.coverage(50) * T * 1.05 * this.kH * r.f(0.9, 1.1));
    const killPer = hp / (N * 0.5 + 3);
    this.push(make.brute(z, r.f(-70, 70), hp, killPer), hintKey);
    const lost = Math.max(0, hp - dps * this.coverage(50) * T * 0.95) / killPer;
    this.est.N = Math.max(1, N - lost);
  };

  Builder.prototype.barrel = function (z, type, x, hintKey) {
    const r = this.rng;
    const N = this.est.N;
    const dps = this.dps();
    const T = this.fireWindow(z, 'barrel');
    const hpMul = { troops: 0.5, weapon: 0.55, rapid: 0.4, bomb: 0.35, freeze: 0.4 }[type];
    // crates are sized for a squad that has missed earlier weapon upgrades
    const safeW = type === 'weapon' ? Math.max(1, this.est.W - 2) : Math.max(1, this.est.W - 1);
    const safeDps = weaponDps(Math.max(1, N * 0.55), safeW);
    const cover = this.coverage(42, N * 0.55);
    const hp = Math.max(3, Math.ceil(safeDps * cover * T * hpMul * r.f(0.85, 1.15)));
    let amount = 0;
    if (type === 'troops') amount = niceRound(N * r.f(0.35, 0.6) + 6);
    if (type === 'bomb') amount = Math.ceil(dps * 6);
    if (x === undefined) x = r.f(-95, 95);
    this.push(make.barrel(z, x, type, hp, amount), hintKey);
    if (type === 'troops') this.est.N = clamp(N + amount * 0.8, 1, C.MAX_SQUAD);
    if (type === 'weapon') this.est.W = Math.min(MAX_WEAPON, this.est.W + 1);
  };

  Builder.prototype.obstacle = function (z, variant, hintKey) {
    const r = this.rng;
    const N = this.est.N;
    if (variant === 'spikes') {
      const side = r.pick(['left', 'right', 'mid']);
      const w = r.f(95, 135);
      let x0;
      if (side === 'left') x0 = -C.ROAD_HALF;
      else if (side === 'right') x0 = C.ROAD_HALF - w;
      else x0 = -w / 2 + r.f(-20, 20);
      this.push(make.spikes(z, x0, x0 + w), hintKey);
    } else if (variant === 'saw') {
      this.push(make.saw(z, r.f(-40, 40), r.f(70, 100), r.f(1.9, 2.9), r.f(0, Math.PI * 2)), hintKey);
    } else {
      const T = this.fireWindow(z, 'static');
      const hp = Math.max(4, Math.ceil(this.dpsSafe() * this.coverage(84, N * 0.55) * T * 0.6 * r.f(0.85, 1.15)));
      this.push(make.tires(z, r.pick([-75, 0, 75]) + r.f(-12, 12), hp, hp / (N * 0.25 + 2)), hintKey);
    }
    this.est.N = Math.max(1, N * 0.97);
  };

  // Places one segment and returns the gap to leave before the next one.
  Builder.prototype.gap = function () {
    return SEG_GAP + 20 - Math.min(90, this.s * 3);
  };

  Builder.prototype.segment = function (z, key) {
    const G = this.gap();
    const hint = key.endsWith('*');
    const k = hint ? key.slice(0, -1) : key;
    const hk = hint ? k : null;
    const [type, variant] = k.split(':');
    const r = this.rng;
    switch (type) {
      case 'gates':
        this.gates(z, variant, hk);
        return G + 90;
      case 'horde':
        this.horde(z, variant, hk);
        return G;
      case 'brute':
        this.brute(z, hk);
        return G;
      case 'barrel':
        this.barrel(z, variant, undefined, hk);
        return G - 60;
      case 'barrel2': {
        const types = r.chance(0.5) ? ['troops', 'weapon'] : ['troops', r.pick(['rapid', 'freeze'])];
        if (this.est.W >= MAX_WEAPON) types[1] = 'rapid';
        if (r.chance(0.5)) types.reverse();
        this.barrel(z, types[0], -75, hk);
        this.barrel(z, types[1], 75);
        return G - 40;
      }
      case 'obst':
        this.obstacle(z, variant, hk);
        return G - 60;
      case 'combo':
        if (variant === 'bombHorde') {
          this.barrel(z, 'bomb', r.f(-40, 40), hk);
          this.horde(z + 260, 'walker', null, 1.7);
          return G + 260;
        }
        if (variant === 'gauntlet') {
          this.obstacle(z, 'saw', hk);
          this.horde(z + 200, 'static', null, 0.8);
          return G + 200;
        }
        this.horde(z, 'walker', hk);
        return G;
      default:
        return G;
    }
  };

  Builder.prototype.bossSpec = function (s, kB) {
    const N = this.est.N;
    // sized so a squad one weapon level short of the plan can still win
    const dps = weaponDps(N, Math.max(1, this.est.W - 1));
    const spec = {
      name: s % 5 === 0 ? '변종 거대 좀비' : '거대 좀비',
      hp: niceRound(dps * 11 * kB),
      dps: Math.max(3, N * 0.14),
      speed: 50,
      homing: 26,
    };
    if (s >= 10) {
      const count = Math.max(4, Math.round(N * 0.12));
      spec.summon = { interval: 4.5, count, zh: Math.max(1, Math.round((dps * 0.8) / count)) };
    }
    return spec;
  };

  // ---------- stage mode ----------
  // Horde and brute pressure: 1.0 means an attentive player can just about shoot everything down.
  function hazardFactor(s) {
    return s <= 3 ? 0.9 : 0.9 + 0.013 * (s - 3);
  }

  function stageFactors(s) {
    const c = CALIB[s - 1];
    if (c) return { kH: c[0], kB: c[1], stars: [c[2], c[3]] };
    return { kH: hazardFactor(s), kB: 2, stars: null };
  }

  function stageLength(s) {
    return 3200 + 110 * s;
  }

  function startCountFor(s) {
    return s <= 3 ? 5 : s <= 10 ? 8 : 10;
  }

  function proceduralPlan(s, rng, nSeg) {
    const plan = new Array(nSeg).fill(null);
    plan[0] = rng.chance(0.5) ? 'gates:easy' : 'gates:addmul';
    plan[nSeg - 1] = rng.chance(0.6) ? 'gates:addmul' : 'gates:bothgood';
    const crates = Math.min(5, 1 + Math.floor(s / 5));
    for (let i = 0; i < crates; i++) {
      let idx = Math.round(((i + 0.6) / (crates + 0.4)) * (nSeg - 2));
      idx = clamp(idx, 1, nSeg - 2);
      while (plan[idx] && idx < nSeg - 2) idx++;
      if (!plan[idx]) plan[idx] = 'barrel:weapon';
    }
    const mid = Math.floor(nSeg / 2);
    let hasMul = false;
    for (let i = 0; i < mid; i++) if (plan[i] === 'gates:addmul') hasMul = true;
    if (!hasMul) {
      for (let i = 1; i < mid; i++) {
        if (!plan[i]) {
          plan[i] = 'gates:addmul';
          break;
        }
      }
    }
    const late = clamp((s - 5) / 25, 0, 1); // 0 at stage 5, 1 at stage 30
    const weights = [
      ['gates:addmul', 11],
      ['gates:easy', 6 - 4 * late],
      ['gates:flip', 6],
      ['gates:lesser', s >= 2 ? 3 + 4 * late : 0],
      ['gates:bothgood', 3],
      ['horde:walker', 16],
      ['horde:static', 9],
      ['horde:runner', s >= 4 ? 5 + 6 * late : 0],
      ['brute', s >= 3 ? 5 + 5 * late : 0],
      ['barrel:troops', 7 - 3 * late],
      ['barrel:rapid', s >= 4 ? 3 : 0],
      ['barrel:freeze', s >= 4 ? 3 : 0],
      ['barrel2', 4],
      ['obst:spikes', s >= 2 ? 5 : 0],
      ['obst:tires', s >= 2 ? 4 : 0],
      ['obst:saw', s >= 3 ? 4 + 3 * late : 0],
      ['combo:bombHorde', s >= 4 ? 4 : 0],
      ['combo:gauntlet', s >= 6 ? 2 + 3 * late : 0],
    ];
    for (let i = 1; i < nSeg; i++) {
      if (plan[i]) continue;
      let pick;
      for (let tries = 0; tries < 12; tries++) {
        pick = rng.weighted(weights);
        const prev = plan[i - 1] || '';
        const prevType = prev.split(':')[0];
        const type = pick.split(':')[0];
        if (type === prevType && tries < 8) continue; // avoid two of a kind in a row
        if (pick === 'horde:runner' && prevType === 'gates' && tries < 10) continue;
        break;
      }
      plan[i] = pick;
    }
    return plan;
  }

  function buildStage(s) {
    const f = stageFactors(s);
    let length = stageLength(s);
    const seed = 1000 + s * 7919;
    const startCount = startCountFor(s);
    const b = new Builder(seed, { startCount, kH: f.kH, s, hints: s <= 5 });
    const nSeg = Math.floor((length - 800) / (b.gap() + 20));
    const plan = INTRO_PLANS[s] ? INTRO_PLANS[s].slice() : proceduralPlan(s, b.rng, nSeg);
    const intro = !!INTRO_PLANS[s];
    let z = 520;
    for (const key of plan) {
      if (!intro && z > length - 250) break;
      b._hinted = false;
      z += b.segment(z, key) + b.rng.f(-40, 40);
    }
    if (intro) length = z + 120;
    const boss = b.bossSpec(s, f.kB);
    const stars = f.stars || [Math.max(2, Math.round(b.est.N * 0.25)), Math.max(3, Math.round(b.est.N * 0.5))];
    return {
      id: s,
      name: 'STAGE ' + s,
      seed,
      length: Math.round(Math.max(length, z + 150)),
      startCount,
      entities: b.ents,
      boss,
      stars,
      bossHint: s === 1 ? '보스 등장! 쓰러질 때까지 계속 쏘세요.' : null,
      est: { N: Math.round(b.est.N), W: b.est.W },
    };
  }

  const cache = {};
  function getStage(s) {
    if (!cache[s]) cache[s] = buildStage(s);
    return cache[s];
  }

  // ---------- endless mode ----------
  const ENDLESS_BOSS_EVERY = 5000;

  function endlessDef() {
    const def = {
      id: 'endless',
      name: '무한 모드',
      endless: true,
      seed: 424242,
      startCount: 10,
      entities: [],
      stars: null,
      length: Infinity,
    };
    def.initGame = function (g) {
      g.gen = {
        b: new Builder(99991, { startCount: 10, kH: 0.8, s: 1 }),
        z: 520,
        level: 1,
        nextBossZ: ENDLESS_BOSS_EVERY,
        segs: 0,
      };
    };
    def.extend = function (g) {
      const gen = g.gen;
      const b = gen.b;
      const limit = Math.min(g.z + 2600, gen.nextBossZ - 300);
      while (gen.z < limit) {
        // the stage adapts halfway toward what the player really has
        b.est.N = clamp(b.est.N * 0.5 + g.count * 0.5, 1, C.MAX_SQUAD);
        b.est.W = Math.max(1, Math.round((b.est.W + g.weapon) / 2));
        b.kH = 0.8 + 0.06 * (gen.level - 1) + g.z / 60000;
        const key = gen.segs === 0 ? 'gates:easy' : nextEndlessKey(b.rng, gen);
        const before = b.ents.length;
        const gap = b.segment(gen.z, key);
        for (let i = before; i < b.ents.length; i++) g.ents.push(Object.assign({}, b.ents[i]));
        b.ents.length = 0;
        gen.z += gap + b.rng.f(-40, 40);
        gen.segs++;
      }
    };
    def.nextBoss = (g) => g.gen.nextBossZ;
    def.makeBoss = function (g) {
      const b = g.gen.b;
      b.est.N = clamp(b.est.N * 0.5 + g.count * 0.5, 1, C.MAX_SQUAD);
      return b.bossSpec(5 + g.gen.level * 3, 0.9 + 0.12 * g.gen.level);
    };
    def.onBossDown = function (g) {
      g.gen.level++;
      g.gen.nextBossZ = g.z + ENDLESS_BOSS_EVERY;
      g.gen.z = Math.max(g.gen.z, g.z + 600);
    };
    return def;
  }

  function nextEndlessKey(rng, gen) {
    const i = gen.segs;
    if (i % 7 === 3 && gen.b.est.W < MAX_WEAPON) return 'barrel:weapon';
    if (i % 4 === 0) return rng.pick(['gates:addmul', 'gates:addmul', 'gates:flip', 'gates:lesser', 'gates:bothgood', 'gates:easy']);
    return rng.weighted([
      ['horde:walker', 14],
      ['horde:static', 8],
      ['horde:runner', 7],
      ['brute', 7],
      ['barrel:troops', 5],
      ['barrel2', 4],
      ['barrel:rapid', 2],
      ['barrel:freeze', 2],
      ['obst:spikes', 5],
      ['obst:tires', 4],
      ['obst:saw', 5],
      ['combo:bombHorde', 3],
      ['combo:gauntlet', 3],
      ['gates:flip', 3],
    ]);
  }

  // ---------- title-screen demo: the classic "wrong door" ad ----------
  function attractDef() {
    const ents = [];
    let pair = 0;
    const gate = (z, l, r) => {
      pair++;
      ents.push(make.gate(z, -C.ROAD_HALF, 0, l.op, l.v, pair, { hpPerPoint: 1.2, soft: 25 }));
      ents.push(make.gate(z, 0, C.ROAD_HALF, r.op, r.v, pair, { hpPerPoint: 1.2, soft: 25 }));
    };
    gate(420, { op: 'add', v: 12 }, { op: 'add', v: -6 });
    ents.push(make.horde(900, -20, 12, 1, 'walker'));
    gate(1250, { op: 'add', v: 8 }, { op: 'mul', v: 2 });
    ents.push(make.barrel(1600, 40, 'weapon', 10, 0));
    ents.push(make.horde(1950, 60, 24, 1, 'static'));
    gate(2350, { op: 'mul', v: 3 }, { op: 'div', v: 2 });
    return {
      id: 'attract',
      name: 'DEMO',
      seed: 5,
      length: 2650,
      startCount: 8,
      entities: ents,
      boss: { name: '거대 좀비', hp: 900, dps: 9, speed: 55, homing: 30 },
      stars: null,
      trapZ: 2350,
    };
  }

  ZGR.Stages = {
    COUNT: STAGE_COUNT,
    CALIB,
    hazardFactor,
    HINTS,
    get: getStage,
    build: buildStage,
    clearCache() {
      for (const k of Object.keys(cache)) delete cache[k];
    },
    endless: endlessDef,
    attract: attractDef,
    niceRound,
  };
})(typeof window !== 'undefined' ? window : globalThis);
